import {useEffect,useRef} from 'react';
import type {PointerEvent} from 'react';
// Ikon mouse gaya gaming: tombol yang aktif terisi penuh, ada tombol samping
// dan garis lampu bawah. Warna mengikuti currentColor agar senada dengan
// tombol HUD; satu-satunya warna tetap adalah aksen lilac lampu bawah karena
// latar HUD selalu gelap.
const MOUSE_BODY='M12 2.2C9.4 2.2 7.3 3.1 6.2 4.9 5 6.9 4.3 10.2 4.35 13.4 4.4 17.6 6.4 21.6 12 21.8c5.6-.2 7.6-4.2 7.65-8.4.05-3.2-.65-6.5-1.85-8.5C16.7 3.1 14.6 2.2 12 2.2Z';
function MouseIcon({right=false}:{right?:boolean}){return <svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={MOUSE_BODY} fill="currentColor" fillOpacity=".05" stroke="none"/><path d={right?'M12.85 2.2v7.85h6.1c-.1-2.7-.6-5.3-1.7-7.05-.55-1.05-2.1-2-3.85-2.3Z':'M11.15 2.2v7.85H5.05c.1-2.7.6-5.3 1.7-7.05C7.85 3.15 9.4 2.2 11.15 2.2Z'} fill="currentColor" stroke="none"/><path d={MOUSE_BODY}/><path d="M4.55 11.2C7 10.4 9.5 10.05 12 10.05c2.5 0 5 .35 7.45 1.15" strokeWidth="1.3"/><path d="M12 2.2v7.85" strokeWidth="1.3"/><path d="M4.75 7.5l1.75.5M4.7 9.9l1.75-.15" strokeOpacity=".45" strokeWidth="1.4"/><path d="M6.7 18.9C8.3 20.8 10.05 21.45 12 21.45c1.95 0 3.7-.65 5.3-2.55" stroke="#A78BFA" strokeWidth="1.5"/></svg>;}
function TrackpadIcon(){return <svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><rect x="3.6" y="4.6" width="16.8" height="14.8" rx="3"/><path d="M3.8 13.6h16.4"/><path d="M9.2 17.3h5.6" stroke="#A78BFA"/><path d="M10.6 15.8 9 17.3l1.6 1.5" stroke="#A78BFA"/><path d="M13.4 15.8l1.6 1.5-1.6 1.5" stroke="#A78BFA"/></svg>;}
function FindCursorIcon(){return <svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinejoin="round" aria-hidden="true"><path d="M5.5 3.5l6.2 14.8 2.3-6.3 6.3-2.3z" fill="currentColor" fillOpacity=".16"/><path d="M5.5 3.5l6.2 14.8 2.3-6.3 6.3-2.3z"/></svg>;}
export function MouseHud({onMouse,onMouseClick,onScroll,onWindows,onCenter,onSwitch,trackpad}:{onMouse:(e:PointerEvent<HTMLButtonElement>,button:number,down:boolean)=>void;onMouseClick:(button:number)=>void;onScroll:(delta:number)=>void;onWindows:(key:string,down:boolean)=>void;onCenter:()=>void;onSwitch:()=>void;trackpad:boolean}){
 const repeat=useRef(new Map<number,ReturnType<typeof setInterval>>());
 const clear=(id:number)=>{const timer=repeat.current.get(id);if(timer!==undefined){clearInterval(timer);repeat.current.delete(id);}};
 const scrollRef=useRef(onScroll);scrollRef.current=onScroll;
 useEffect(()=>{const reset=()=>{for(const id of repeat.current.keys())clear(id);};const visibility=()=>{if(document.hidden)reset();};window.addEventListener('blur',reset);document.addEventListener('visibilitychange',visibility);return()=>{reset();window.removeEventListener('blur',reset);document.removeEventListener('visibilitychange',visibility);};},[]);
 return <div className="hud-mouse" aria-label="Kontrol mouse">
 {[0,1].map(button=><button key={button} type="button" className="hud-icon-btn" aria-label={button?'Klik kanan':'Klik kiri'} title={button?'Klik kanan':'Klik kiri — tahan untuk drag'} onPointerDown={e=>onMouse(e,button,true)} onPointerUp={e=>onMouse(e,button,false)} onPointerCancel={e=>onMouse(e,button,false)} onLostPointerCapture={e=>onMouse(e,button,false)} onContextMenu={e=>e.preventDefault()} onClick={e=>{if(e.detail===0)onMouseClick(button);}}><MouseIcon right={button===1}/></button>)}
 {[120,-120].map(delta=><button key={delta} type="button" className="hud-icon-btn" aria-label={delta>0?'Scroll atas':'Scroll bawah'} onPointerDown={e=>{e.preventDefault();e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);clear(e.pointerId);scrollRef.current(delta);repeat.current.set(e.pointerId,setInterval(()=>scrollRef.current(delta),100));}} onPointerUp={e=>clear(e.pointerId)} onPointerCancel={e=>clear(e.pointerId)} onLostPointerCapture={e=>clear(e.pointerId)} onClick={e=>{if(e.detail===0)scrollRef.current(delta);}}><svg viewBox="0 0 24 24" width="23" height="23" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><path d={delta>0?'m6 14 6-6 6 6':'m6 10 6 6 6-6'}/></svg></button>)}
 <button type="button" className="hud-icon-btn" aria-label="Tombol Windows" onPointerDown={e=>{e.preventDefault();e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);onWindows(String(e.pointerId),true);}} onPointerUp={e=>onWindows(String(e.pointerId),false)} onPointerCancel={e=>onWindows(String(e.pointerId),false)} onLostPointerCapture={e=>onWindows(String(e.pointerId),false)} onClick={e=>{if(e.detail===0){onWindows('keyboard',true);onWindows('keyboard',false);}}}><svg viewBox="0 0 24 24" width="22" height="22" fill="currentColor" aria-hidden="true"><path d="M3 3h8v8H3zm10 0h8v8h-8zM3 13h8v8H3zm10 0h8v8h-8z"/></svg></button>
 <button type="button" className="hud-icon-btn" aria-label="Switch langsung / trackpad" aria-pressed={trackpad} onClick={onSwitch} title={trackpad?'Trackpad aktif':'Sentuh langsung aktif'}><TrackpadIcon/></button>
 <button type="button" className="hud-icon-btn" aria-label="Temukan panah" onClick={onCenter}><FindCursorIcon/></button>
 </div>;
}
