import {useEffect,useRef,useState} from 'react';
import type {PointerEvent} from 'react';
function MouseIcon({right=false}:{right?:boolean}){return <svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><rect x="5" y="2" width="14" height="20" rx="7"/><path d="M12 2v8M5 10h14"/><path d={right?'M13 4a5 5 0 0 1 4 5h-4z':'M11 4a5 5 0 0 0-4 5h4z'} fill="currentColor" stroke="none"/></svg>;}
type DockPrefs={side:'left'|'right';large:boolean};
const KEY='xydesk.mouse.dock.v1';
function loadPrefs():DockPrefs {try{const p=JSON.parse(localStorage.getItem(KEY)||'{}');return {side:p.side==='left'?'left':'right',large:p.large!==false};}catch{return {side:'right',large:true};}}
export function MouseHud({onMouse,onMouseClick,onScroll,onWindows,onCenter,onSwitch,onCustomize,onRelease,trackpad}:{onMouse:(e:PointerEvent<HTMLButtonElement>,button:number,down:boolean)=>void;onMouseClick:(button:number)=>void;onScroll:(delta:number)=>void;onWindows:(key:string,down:boolean)=>void;onCenter:()=>void;onSwitch:()=>void;onCustomize:()=>void;onRelease:()=>void;trackpad:boolean}){
 const [prefs,setPrefs]=useState(loadPrefs),[settings,setSettings]=useState(false);
 const repeat=useRef(new Map<number,ReturnType<typeof setInterval>>());
 const clear=(id:number)=>{const timer=repeat.current.get(id);if(timer!==undefined){clearInterval(timer);repeat.current.delete(id);}};
 const scrollRef=useRef(onScroll);scrollRef.current=onScroll;
 const releaseRef=useRef(onRelease);releaseRef.current=onRelease;
 useEffect(()=>{try{localStorage.setItem(KEY,JSON.stringify(prefs));}catch{}},[prefs]);
 useEffect(()=>{const reset=()=>{for(const id of repeat.current.keys())clear(id);releaseRef.current();};const visibility=()=>{if(document.hidden)reset();};window.addEventListener('blur',reset);document.addEventListener('visibilitychange',visibility);return()=>{reset();window.removeEventListener('blur',reset);document.removeEventListener('visibilitychange',visibility);};},[]);
 return <div className={`mouse-dock ${prefs.side} ${prefs.large?'comfortable':'compact'}`} aria-label="Kontrol mouse" onContextMenu={e=>e.preventDefault()}>
 <div className="mouse-dock-header"><span>{trackpad?'Mode trackpad':'Sentuh langsung'}<small>Tahan klik kiri untuk drag</small></span><button type="button" aria-expanded={settings} onClick={()=>setSettings(v=>!v)}>Atur dock</button></div>
 {settings&&<div className="mouse-dock-settings"><label>Posisi<select value={prefs.side} onChange={e=>setPrefs(p=>({...p,side:e.target.value==='left'?'left':'right'}))}><option value="left">Kiri</option><option value="right">Kanan</option></select></label><label><input type="checkbox" checked={prefs.large} onChange={e=>setPrefs(p=>({...p,large:e.target.checked}))}/> Tombol besar</label><button type="button" onClick={onCustomize}>Edit tombol dan shortcut bebas</button></div>}
 <div className="mouse-dock-buttons">
 {[0,1].map(button=><button key={button} type="button" className="dock-mouse-primary" aria-label={button?'Klik kanan':'Klik kiri'} title={button?'Klik kanan':'Klik kiri — tahan untuk drag; dua ketukan untuk double click'} onPointerDown={e=>onMouse(e,button,true)} onPointerUp={e=>onMouse(e,button,false)} onPointerCancel={e=>onMouse(e,button,false)} onLostPointerCapture={e=>onMouse(e,button,false)} onClick={e=>{if(e.detail===0)onMouseClick(button);}}><MouseIcon right={button===1}/><span>{button?'Klik kanan':'Klik kiri'}</span></button>)}
 {[120,-120].map(delta=><button key={delta} type="button" aria-label={delta>0?'Scroll atas':'Scroll bawah'} onPointerDown={e=>{e.preventDefault();e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);clear(e.pointerId);scrollRef.current(delta);repeat.current.set(e.pointerId,setInterval(()=>scrollRef.current(delta),100));}} onPointerUp={e=>clear(e.pointerId)} onPointerCancel={e=>clear(e.pointerId)} onLostPointerCapture={e=>clear(e.pointerId)} onClick={e=>{if(e.detail===0)scrollRef.current(delta);}}><svg viewBox="0 0 24 24" width="23" height="23" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><path d={delta>0?'m6 14 6-6 6 6':'m6 10 6 6 6-6'}/></svg><span>{delta>0?'Scroll atas':'Scroll bawah'}</span></button>)}
 <button type="button" aria-label="Tombol Windows" onPointerDown={e=>{e.preventDefault();e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);onWindows(String(e.pointerId),true);}} onPointerUp={e=>onWindows(String(e.pointerId),false)} onPointerCancel={e=>onWindows(String(e.pointerId),false)} onLostPointerCapture={e=>onWindows(String(e.pointerId),false)} onClick={e=>{if(e.detail===0){onWindows('keyboard',true);onWindows('keyboard',false);}}}>Windows</button>
 <button type="button" aria-label="Ganti mode trackpad" aria-pressed={trackpad} onClick={onSwitch}>{trackpad?'Trackpad aktif':'Sentuh aktif'}</button>
 <button type="button" onClick={onCenter}>Pusatkan kursor</button><button type="button" onClick={onCustomize}>Layout custom</button>
 </div></div>;
}
